### ISSUE TITLE
Still used in Plone 6?

### ISSUE THREAD

**Issue by gforcada** [collective/Products.DateRecurringIndex#9]
Is it worth converting it to use `plone/meta`? 🤔

**Comment by davisagli** [comment]
@gforcada Yes, still actively used afaik

**Comment by gforcada** [comment]
But not in core itself? I don't see it on `bin/instance` 🤔

**Comment by davisagli** [comment]
It's a dependency of plone.app.event: https://github.com/plone/plone.app.event/blob/master/setup.py#L51

**Comment by gforcada** [comment]
Oh, I see, thanks! 👍🏾
